name: minerasys_app
description: Minerasys - Sistema de Controle de Areal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP e API
  dio: ^5.4.0
  http: ^1.1.0
  
  # Armazenamento Local
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # Conectividade
  connectivity_plus: ^5.0.2
  
  # UI/UX
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  
  # Ãcones
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/